use topcoat_core::context::Cx;

use crate::runtime::View;

/// A renderable component.
///
/// Implementations are usually generated by Topcoat's component macro. Manual
/// implementations receive the current context and child content, then return
/// a rendered [`View`] or an error.
pub trait Component {
    /// The error returned when rendering fails.
    type Error;

    /// Renders this component with the provided context and child view.
    fn render(self, cx: &Cx, child: View)
    -> impl Future<Output = Result<View, Self::Error>> + Send;
}
